---
'N': 1
adversarial: true
amp: false
batch_size: 1024
batchnorm: false
bins:
  - 100
  - 100
  - 100
  - 100
ckpt: false
ckpt_flow: ''
cond_dim: 1
context_features: 5
coupling_hidden: 256
coupling_layers: 20
dataset: jet
decay: 0.999
dropout: 0
ema: true
ema_start: 50000
freq: 1
gan: lsgan
gp: false
heads: 4
heads_gen: 8
hidden: 32
hidden_features: 128
hidden_gen: 256
lambda_dis: 0.1
l_dim: 16
l_dim_gen: 16
lr: 0.0001
mass_loss: false
max: false
max_epochs: 2000
mean_field_loss: true

model: PNF
n_dim: 3
n_part: 30
name: jet_pnf
network_layers: 4
noise: false
num_bins: 8
num_heads: 8
num_layers: 2
num_layers_gen: 7
opt: AdamW
parton: t
pretrain: false
sampler: false
spline: true
tail_bound: 6
weightdecay: 0