---
avg_n: 70
batch_size: 2048
bins:
  - 100
  - 45
  - 50
  - 18
names:
  - E
  - z
  - a
  - R
boxcox: false
cond_dim: 2
continue: false
ckpt: "ckpts/mdma_calo_fm_small.ckpt"
dataset: calo
decay: 0.999
dropout: 0
drop_last: true
E_loss: false
ema: false
ema_start: 50000
frequencies: 8
exact: false
glu: true
heads: 16
hidden_dim: 512
lambda_gp:  0
lambda_response: 0.
latent: 16
layers: 16
lr: 0.00001
max: true
max_epochs: 200
max_tokens: 1600_000
model: FM
middle: false
n_dim: 4
n_part: 10000
name: calo
num_heads: 16
opt: AdamW
parton: t
raw: false
sampler: true
t_local_cat: true
t_global_cat: true
weightdecay: 0.000005