---

'N': 1
amp: false
batch_size: 128
bins:
  - 100
  - 100
  - 100
  - 100
ckpt: ''
cloudnorm: false
cloudnormgen: false
cond_dim: 1
dataset: jet
decay: 0.999
dropout: 0.0
ema: false
ema_start: 50000
fid: false
freq: 1
gan: lsgan
glu: false
gp: false
gp_weight: 0.1
heads: 8
heads_gen: 8
hidden: 128
hidden_gen: 128
l_dim: 16
l_dim_gen: 16
lambda_gp: 10
lr: 0.0001
max: true
max_epochs: 2000
mean_field_loss: true
model: MDMA
n_dim: 3
n_part: 150
name: jet
noise: false
num_layers: 3
num_layers_gen: 4
opt: Adam
parton: t
pretrain: false
sampler: true
spectralnorm: true
stop_mean: false
weightdecay: 0.0
weightnorm: false