---
batch_size: 256
batchnorm: false
bins:
  - 100
  - 100
  - 100
  - 100
boxcox: true
ckpt: ''
ckpt_flow: ./ckpts/t_nf.ckpt
cond_dim: 0
context_features: 0
coupling_hidden: 256
coupling_layers: 10
dataset: jet
decay: 0.999
dropout: 0
ema: false
ema_start: 50000
fast: false
freq: 1
gan: lsgan
gp: false
heads: 16
hidden: 256
hidden_features: 256
l_dim: 16
lr: 0.0001
mass_loss: false
max: true
max_epochs: 2000
mean_field_loss: true
model: TNF
n_dim: 3
n_part: 30
name: jet_tnf
network_layers: 6
norm: false
num_bins: 8
num_heads: 16
num_layers: 4
opt: AdamW
parton: t
sampler: true
spline: true
tail_bound: 6
weightdecay: 0.01