avg_n: 70
E_loss: true
L2: false
'N': 1
adversarial: true
amp: false
augmentation: false
batch_size: 64
bins:
  - 100
  - 45
  - 16
  - 9
ckpt: 'ckpts/mdma_calo.ckpt'
continue: false
cloudnorm: false
cloudnormgen: false
cond_dim: 2
dataset: calo
decay: 0.999
dropout: 0.0
ema: false
ema_start: 500000
fid: false
freq: 3
gan: wgan
glu: true
gp: true
heads: 8
heads_gen: 16
hidden: 64
hidden_gen: 128
l_dim: 16
l_dim_gen: 16
lambda: 0.1
lambda_gp: 10
lambda_response: 0.1
lr: 0.0001
max: false
max_epochs: 2000
mean_field_loss: true
model: MDMA
n_dim: 4
name: calo
names:
  - E
  - z
  - alpha
  - R
noise: true
num_R: 9
num_alpha: 16
num_layers: 4
num_layers_gen: 6
num_z: 45
opt: AdamW
sampler: true
spectralnorm: false
stop_mean: true
t_local_cat: true
t_global_cat: true
weightnorm: true
weightdecay: 0.000005