---
batch_size: 256
bins:
  - 100
  - 100
  - 100
  - 100
boxcox: true
ckpt: 'ckpts/t_tf.ckpt'
cond_dim: 0
dataset: jet
decay: 0.999
dropout: 0
ema: true
ema_start: 5000
fast: false
freq: 1
gan: lsgan
gp: false
hidden: 128
l_dim: 16
lr: 0.00001
max: true
max_epochs: 4000
mean_field_loss: true
model: TF
n_dim: 3
n_part: 30
name: jet_tf
noise: true
norm: false
num_heads: 16
num_layers: 4
opt: AdamW
parton: t
pretrain: false
sampler: true
spectralnorm: false
stop_mean: true
weightdecay: 0.01
weightnorm: false