---

'N': 1
amp: false
batch_size: 128
bins:
  - 100
  - 100
  - 100
  - 100
boxcox: false
ckpt: ''
cloudnorm: false
cloudnormgen: false
cond_dim: 1
dataset: jet
decay: 0.999
dropout: 0.0
ema: false
ema_start: 50000
fid: false
freq: 1
gan: lsgan
glu: false
gp: false
gp_weight: 0.1
heads: 16
heads_gen: 16
hidden: 64
hidden_gen: 48
l_dim: 16
l_dim_gen: 16
lambda_gp: 10
lr: 0.0001
max: true
max_epochs: 2000
mean_field_loss: true
model: MDMA
n_dim: 3
n_part: 150
name: jet
noise: true
num_layers: 2
num_layers_gen: 7
opt: Adam
parton: t
pretrain: false
sampler: false
spectralnorm: false
stop_mean: false
weightdecay: 0.0
weightnorm: true