---
avg_n: 70
batch_size: 128
bins:
  - 100
  - 45
  - 50
  - 18
names:
  - E
  - z
  - a
  - R
boxcox: false
cond_dim: 2
ckpt: "./ckpts/mdma_fm_calo.ckpt"
dataset: calo
decay: 0.999
dropout: 0
E_loss: false
ema: false
ema_start: 50000
frequencies: 8
exact: false
glu: true
heads: 8
hidden_dim: 1024
lambda_gp:  0
lambda_response: 0.
latent: 64
layers: 8
lr: 0.00001
max: true
max_epochs: 500
model: FM
middle: false
n_dim: 4
n_part: 10000
name: calo
num_heads: 32
opt: AdamW
parton: t
sampler: true
t_local_cat: true
t_global_cat: true
weightdecay: 0.000005