---
avg_n: 70
batch_size: 1024
bins:
  - 100
  - 100
  - 100
  - 100
boxcox: false
cond_dim: 1
ckpt: "ckpts/mdma_fm_jet.ckpt"
dataset: jet
decay: 0.999
dropout: 0
ema: false
ema_start: 1000
frequencies: 16
exact: false
glu: false
hidden_dim: 64
latent: 16
layers: 16
lr: 0.000001
max: true
max_epochs: 2000
model: FM
n_dim: 3
n_part: 150
name: jet
num_heads: 8
opt: AdamW
parton: t
sampler: true
weightdecay: 0.01