'N': 1
amp: false
batch_size: 1024
batchnorm: true
bins:
  - 100
  - 100
  - 100
  - 100
ckpt: "ckpts/t_cnf.ckpt"
cond_dim: 1
context_features: 1
coupling_hidden: 128
coupling_layers: 25
dataset: jet
decay: 0.999
dropout: 0
ema: false
ema_start: 50000
gan: lsgan
gp: false
hidden: 256
hidden_features: 156
hidden_gen: 128
l_dim: 16
l_dim_gen: 16
lambda_m: 1
lr: 0.0002
mass_loss: true
max: false
max_epochs: 1000
mean_field_loss: true
model: NF
n_dim: 3
n_part: 30
name: jet_nf
network_layers: 3
num_bins: 6
num_layers: 2
opt: AdamW
parton: t
pretrain: false
sampler: false
spline: true
tail_bound: 5
weightdecay: 0.01